### ISSUE TITLE
Artwork isn't rendered in the right size

### ISSUE THREAD

**Issue by ghost** [din/simplify_jackets#4]
The album artwork is rendered too small sometimes.
Works well with bowtie, but doesn't work with simplify even though I'm using the Simplify API.

**Comment by din** [comment]
Yeah, we already are aware of that, but we cannot provide the fix as an update yet. Still, you can use our temporary fix. http://mmth.us/simplify/support.html#hotfix

**Comment by ghost** [comment]
It's not about the default skins.
I'm currently working on my own jacket and "background-size" with the exact pixels doesn't work.
Will this be fixed in the next version or do I have to implement the cover by another way?

**Comment by din** [comment]
No, this is a Webkit issue, not a Simplify one. You need to modify your CSS to be like that:

``` css
.element
{
    /* Note this line, you should add !important now */
    -webkit-background-size: cover !important;
    width: 250px;
    height: 250px;
}
```

Please tell me if that helped.
